apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: jenkins-oscar
    provider: github
    repository: carros
  name: jenkins-oscar-carros
spec:
  description: Imported application for jenkins-oscar/carros
  httpCloneURL: https://github.com/jenkins-oscar/carros.git
  org: jenkins-oscar
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: carros
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/jenkins-oscar/carros.git
